name: PHP PSR-12 Validation

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    
    - name: Run PSR-12 Validation
      run: vendor/bin/phpcs src --standard=PSR12

    - name: Run test suite
      run: vendor/phpunit/phpunit/phpunit -c phpunit.xml --coverage-clover=coverage.xml